# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustySearch < Formula
  desc "trusty-tools: trusty-search binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.34.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-search-v0.34.0/trusty-search-0.34.0-aarch64-apple-darwin.tar.gz"
      sha256 "d49da5135ac94186ca8b5896dabbc83b38d70947a7945c73882c6bb0e9ba5277"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-search-v0.34.0/trusty-search-0.34.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ced499c32876da06c8d6c67d3e3a836ea2cdd34843d13e682dd89e25423a1094"
    end
  end

  def install
    bin.install "trusty-search"
    bin.install "trusty-embedderd"
  end

  test do
    system bin/"trusty-search", "--version"
  end
end
