# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyConsole < Formula
  desc "trusty-tools: trusty-console binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.7.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-console-v0.7.0/trusty-console-0.7.0-aarch64-apple-darwin.tar.gz"
      sha256 "666ddcf69595cce4dc9d2ceb59a45c043002070d5c6d17aaef27db2706acbc6b"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-console-v0.7.0/trusty-console-0.7.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "02b417e920f6b29c72600ad326ebf10eec6098949ae360c35cc8523fcdd50067"
    end
  end

  def install
    bin.install "trusty-console"
  end

  test do
    system bin/"trusty-console", "--version"
  end
end
