# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyMpm < Formula
  desc "trusty-tools: trusty-mpm binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "1.3.3"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-mpm-v1.3.3/trusty-mpm-1.3.3-aarch64-apple-darwin.tar.gz"
      sha256 "45d1a44d1f0a75eccefd3b0919d181e890bc78e0be5f5274f31b64267f0852f0"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-mpm-v1.3.3/trusty-mpm-1.3.3-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "eb2d8eb468988bcf7b2542b034c2a6a623fe281e7ccfb435a5b15aed05bd6c8a"
    end
  end

  def install
    bin.install "tm"
    bin.install "trusty-mpm"
  end

  test do
    system bin/"tm", "--version"
  end
end
