# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyReview < Formula
  desc "trusty-tools: trusty-review binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.36.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-review-v0.36.0/trusty-review-0.36.0-aarch64-apple-darwin.tar.gz"
      sha256 "2355969d5a2227a6d0ad30211ae6b43c500d0a94f8b281fa893643833500ee28"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-review-v0.36.0/trusty-review-0.36.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e49a6bf9391194b4ec33913d6c1219490306c6bacc2f6dc7270e0f54ba19b58b"
    end
  end

  def install
    bin.install "trusty-review"
  end

  test do
    system bin/"trusty-review", "--version"
  end
end
