# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyCode < Formula
  desc "trusty-tools: trusty-code binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.5.1"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-code-v0.5.1/trusty-code-0.5.1-aarch64-apple-darwin.tar.gz"
      sha256 "394579bdc23e3e594e17ff2eac6f0f9fd04747e9b7f6f76d5f2b85201851178f"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-code-v0.5.1/trusty-code-0.5.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0e7e7b3976b1075588e693f497ae39b38906e1c0cd2a01822081c2742abfecc6"
    end
  end

  def install
    bin.install "tcode"
  end

  test do
    system bin/"tcode", "--version"
  end
end
