# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyController < Formula
  desc "trusty-tools: trusty-controller binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.2.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-controller-v0.2.0/trusty-controller-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "b0c28ee121db9692cc94af921c355f8926ce49a2f57cbfc190713c295fa3e696"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-controller-v0.2.0/trusty-controller-0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1f2535edea2c6134b8f72d7f1f717a2c465bb1fe9f95d73efe0a27b72ab13ee3"
    end
  end

  def install
    bin.install "tctl"
  end

  test do
    system bin/"tctl", "--version"
  end
end
