# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyAnalyze < Formula
  desc "trusty-tools: trusty-analyze binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.12.6"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-analyze-v0.12.6/trusty-analyze-0.12.6-aarch64-apple-darwin.tar.gz"
      sha256 "caab668da4064222ad2becf2885ee59c3d846a7a92daf8ec8dcfad68a617dd5f"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-analyze-v0.12.6/trusty-analyze-0.12.6-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "12b77eadbbf6fccde9c8df0913af7a642fea5e29faa605191875bede8809a439"
    end
  end

  def install
    bin.install "trusty-analyze"
  end

  test do
    system bin/"trusty-analyze", "--version"
  end
end
