# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyMpm < Formula
  desc "trusty-tools: trusty-mpm binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "1.5.10"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-mpm-v1.5.10/trusty-mpm-1.5.10-aarch64-apple-darwin.tar.gz"
      sha256 "24a6b001b93603e8aad6efc1d5d50951634b8fd74430284624412fd370e89802"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-mpm-v1.5.10/trusty-mpm-1.5.10-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "294135796c25d701608702482d75176921226a9eebe8a7caf3c26ff45602ecd0"
    end
  end

  def install
    bin.install "tm"
    bin.install "trusty-mpm"
  end

  test do
    system bin/"tm", "--version"
  end
end
