# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyConsole < Formula
  desc "trusty-tools: trusty-console binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.5.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-console-v0.5.0/trusty-console-0.5.0-aarch64-apple-darwin.tar.gz"
      sha256 "35bcc4bedd4efe205ec357bdb50b03f43f86d6451af352aba63c35b7616fd403"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-console-v0.5.0/trusty-console-0.5.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "70309dc97f2e23e476b6845b6f2840d01f7a5007768ef807d0a52317745b6d4b"
    end
  end

  def install
    bin.install "trusty-console"
  end

  test do
    system bin/"trusty-console", "--version"
  end
end
