# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyCode < Formula
  desc "trusty-tools: trusty-code binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.4.1"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-code-v0.4.1/trusty-code-0.4.1-aarch64-apple-darwin.tar.gz"
      sha256 "3cf7fb3b20b2f15abafb27ef2fac670f350706e50c408449b7fd2637469c0fe9"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-code-v0.4.1/trusty-code-0.4.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a1da3d08b81dec692ed86494a68bc39ed870fa6797ec754f78b8a85a1d600536"
    end
  end

  def install
    bin.install "tcode"
  end

  test do
    system bin/"tcode", "--version"
  end
end
