# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyReview < Formula
  desc "trusty-tools: trusty-review binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.12.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-review-v0.12.0/trusty-review-0.12.0-aarch64-apple-darwin.tar.gz"
      sha256 "d760a6fbd4200a65d7bba36866084c18c3c879820ea3c9c4879ebc0ff200f561"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-review-v0.12.0/trusty-review-0.12.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1ae0e79d39459239d4d103e9d09de34c35a1315f7ba9603e648b7cc3488e1255"
    end
  end

  def install
    bin.install "trusty-review"
  end

  test do
    system bin/"trusty-review", "--version"
  end
end
