# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustySearch < Formula
  desc "trusty-tools: trusty-search binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.57.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-search-v0.57.0/trusty-search-0.57.0-aarch64-apple-darwin.tar.gz"
      sha256 "dfd9dcf5a86027de43e437f0b66ac5739f29eb8d8e6952543c3025c6e83997df"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-search-v0.57.0/trusty-search-0.57.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "97171df97f1db531f9796787baa64a9c7420c18ce38048b7a0c208467a0fb726"
    end
  end

  def install
    bin.install "trusty-search"
    bin.install "trusty-embedderd"
  end

  test do
    system bin/"trusty-search", "--version"
  end
end
