# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyGitAnalytics < Formula
  desc "trusty-tools: trusty-git-analytics binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "2.8.2"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/tga-v2.8.2/trusty-git-analytics-2.8.2-aarch64-apple-darwin.tar.gz"
      sha256 "cf72deaca43c05f9461073275a80feb9d10817cacdea6819b6786790607318ae"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/tga-v2.8.2/trusty-git-analytics-2.8.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "6e39f96aa47fbfc3732e9d919e978a3f66bf98ed90cd90b9c46e979c66cfb77f"
    end
  end

  def install
    bin.install "tga"
  end

  test do
    system bin/"tga", "--version"
  end
end
