# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyAudit < Formula
  desc "trusty-tools: trusty-audit binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.6.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-audit-v0.6.0/trusty-audit-0.6.0-aarch64-apple-darwin.tar.gz"
      sha256 "c89cd7ad9438b876ba83c346ea013aa81cebee74d3810ece4817b1aff2bd005f"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-audit-v0.6.0/trusty-audit-0.6.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "81522d1407e2fc630c331a8ea71bb8969ef911dfa3a4e2fc30b3691ac9f71a1c"
    end
  end

  def install
    bin.install "trusty-audit"
    bin.install "taudit"
  end

  test do
    system bin/"trusty-audit", "--version"
  end
end
