# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyInstaller < Formula
  desc "trusty-tools: trusty-installer binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.13.8"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-installer-v0.13.8/trusty-installer-0.13.8-aarch64-apple-darwin.tar.gz"
      sha256 "0fd3c7165b6175e164b4864385d0e4eed1afc753ce6e164c46c9056dcc67dce3"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-installer-v0.13.8/trusty-installer-0.13.8-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2c6c12ce34cf2faf91d7a9f20ef897188a766f1b80b9f618558ed0e11bc4dc53"
    end
  end

  def install
    bin.install "trusty-installer"
    bin.install "tctl"
  end

  test do
    system bin/"trusty-installer", "--version"
  end
end
