# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyReview < Formula
  desc "trusty-tools: trusty-review binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.10.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-review-v0.10.0/trusty-review-0.10.0-aarch64-apple-darwin.tar.gz"
      sha256 "0b3ce46f00d12d037073d207ae920d9089e18a162c58abe64742598a0dd0d2c1"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-review-v0.10.0/trusty-review-0.10.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "af3ccbe09ca0899184f7c0f60c718d1c6d0ebe01455a718cd1b067e7eb603462"
    end
  end

  def install
    bin.install "trusty-review"
  end

  test do
    system bin/"trusty-review", "--version"
  end
end
