# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyAudit < Formula
  desc "trusty-tools: trusty-audit binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.14.1"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-audit-v0.14.1/trusty-audit-0.14.1-aarch64-apple-darwin.tar.gz"
      sha256 "5e6a1b38f2b51a4f82f1ab7cf415fb39b7040088ea2d02806f7c27197ee9eaf6"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-audit-v0.14.1/trusty-audit-0.14.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "865cf0ef2777be5795fd0a3cd7cfc34263cf77a5a5d5b3a60c4ec4dd705cc03d"
    end
  end

  def install
    bin.install "trusty-audit"
    bin.install "taudit"
  end

  test do
    system bin/"trusty-audit", "--version"
  end
end
