# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyMemory < Formula
  desc "trusty-tools: trusty-memory binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.27.1"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-memory-v0.27.1/trusty-memory-0.27.1-aarch64-apple-darwin.tar.gz"
      sha256 "c892c2a5acfe88e79252f9399cdcec1fe3c5ca9ab8c99a7b1f1693bb72f068db"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-memory-v0.27.1/trusty-memory-0.27.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "174c59c5af7c7c2948263a614326e3e6b688cd93646331c7e06fba5259a7cfff"
    end
  end

  def install
    bin.install "trusty-memory"
  end

  test do
    system bin/"trusty-memory", "--version"
  end
end
