# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustySearch < Formula
  desc "trusty-tools: trusty-search binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.32.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-search-v0.32.0/trusty-search-0.32.0-aarch64-apple-darwin.tar.gz"
      sha256 "f52ecfc3cc34aea1fba04da799606c3c31a678ad502867742e7e8e2d6a24bb2d"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-search-v0.32.0/trusty-search-0.32.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "3fd14172e8295b33e4519c04caeb4682a9a039c0f39f78ffd79048607012ae4b"
    end
  end

  def install
    bin.install "trusty-search"
    bin.install "trusty-embedderd"
  end

  test do
    system bin/"trusty-search", "--version"
  end
end
